CONFIG_CAN=y
CONFIG_CAN_STATS=y
CONFIG_GPIO=y
CONFIG_COUNTER=y
# Log settings help with debugging if the bus goes off
CONFIG_LOG=y
CONFIG_LOG_MODE_DEFERRED=y
#CONFIG_CAN_LOG_LEVEL_DBG=y
#CONFIG_CAN_LOG_LEVEL_WRN=y

# Give CAN interrupts higher priority
CONFIG_CAN_INIT_PRIORITY=41

# Increase system clock if not already at max
#           CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC=168000000
#CONFIG_SYSTEM_CLOCK_HW_CYCLES_PER_SEC_RUNTIME_UPDATE=y

# Optimize kernel
CONFIG_SCHED_SCALABLE=y
CONFIG_TIMESLICING=n

CONFIG_CLOCK_CONTROL=y


# Need to check below settings for logging and shell, as they can cause performance issues
#CONFIG_LOG_BACKEND_UART_OUTPUT_DICTIONARY_HEX=n
#CONFIG_SHELL_VT100_COLORS=n